### This analysis was done in excel. I mentioned it in python as a more appropriate tool.

link of excercise:
https://www.coursera.org/learn/big-data-management/supplement/SBtIc/exploring-the-relational-data-model-of-comma-separated-values-csv

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('census.csv')

In [7]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2875 entries, 0 to 2874
Data columns (total 100 columns):
SUMLEV                   2875 non-null int64
REGION                   2875 non-null int64
DIVISION                 2875 non-null int64
STATE                    2875 non-null int64
COUNTY                   2875 non-null int64
STNAME                   2875 non-null object
CTYNAME                  2875 non-null object
CENSUS2010POP            2875 non-null int64
ESTIMATESBASE2010        2875 non-null int64
POPESTIMATE2010          2875 non-null int64
POPESTIMATE2011          2875 non-null int64
POPESTIMATE2012          2875 non-null int64
POPESTIMATE2013          2875 non-null int64
POPESTIMATE2014          2875 non-null int64
POPESTIMATE2015          2875 non-null int64
NPOPCHG_2010             2875 non-null int64
NPOPCHG_2011             2875 non-null int64
NPOPCHG_2012             2875 non-null int64
NPOPCHG_2013             2875 non-null int64
NPOPCHG_2014             2875 non-null int64
NPOPCHG_2015             2875 non-null int64
BIRTHS2010               2875 non-null int64
BIRTHS2011               2875 non-null int64
BIRTHS2012               2875 non-null int64
BIRTHS2013               2875 non-null int64
BIRTHS2014               2875 non-null int64
BIRTHS2015               2875 non-null int64
DEATHS2010               2875 non-null int64
DEATHS2011               2875 non-null int64
DEATHS2012               2875 non-null int64
DEATHS2013               2875 non-null int64
DEATHS2014               2875 non-null int64
DEATHS2015               2875 non-null int64
NATURALINC2010           2875 non-null int64
NATURALINC2011           2875 non-null int64
NATURALINC2012           2875 non-null int64
NATURALINC2013           2875 non-null int64
NATURALINC2014           2875 non-null int64
NATURALINC2015           2875 non-null int64
INTERNATIONALMIG2010     2875 non-null int64
INTERNATIONALMIG2011     2875 non-null int64
INTERNATIONALMIG2012     2875 non-null int64
INTERNATIONALMIG2013     2875 non-null int64
INTERNATIONALMIG2014     2875 non-null int64
INTERNATIONALMIG2015     2875 non-null int64
DOMESTICMIG2010          2875 non-null int64
DOMESTICMIG2011          2875 non-null int64
DOMESTICMIG2012          2875 non-null int64
DOMESTICMIG2013          2875 non-null int64
DOMESTICMIG2014          2875 non-null int64
DOMESTICMIG2015          2875 non-null int64
NETMIG2010               2875 non-null int64
NETMIG2011               2875 non-null int64
NETMIG2012               2875 non-null int64
NETMIG2013               2875 non-null int64
NETMIG2014               2875 non-null int64
NETMIG2015               2875 non-null int64
RESIDUAL2010             2875 non-null int64
RESIDUAL2011             2875 non-null int64
RESIDUAL2012             2875 non-null int64
RESIDUAL2013             2875 non-null int64
RESIDUAL2014             2875 non-null int64
RESIDUAL2015             2875 non-null int64
GQESTIMATESBASE2010      2875 non-null int64
GQESTIMATES2010          2875 non-null int64
GQESTIMATES2011          2875 non-null int64
GQESTIMATES2012          2875 non-null int64
GQESTIMATES2013          2875 non-null int64
GQESTIMATES2014          2875 non-null int64
GQESTIMATES2015          2875 non-null int64
RBIRTH2011               2875 non-null float64
RBIRTH2012               2875 non-null float64
RBIRTH2013               2875 non-null float64
RBIRTH2014               2875 non-null float64
RBIRTH2015               2875 non-null float64
RDEATH2011               2875 non-null float64
RDEATH2012               2875 non-null float64
RDEATH2013               2875 non-null float64
RDEATH2014               2875 non-null float64
RDEATH2015               2875 non-null float64
RNATURALINC2011          2875 non-null float64
RNATURALINC2012          2875 non-null float64
RNATURALINC2013          2875 non-null float64
RNATURALINC2014          2875 non-null float64
RNATURALINC2015          2875 non-null float64
RINTERNATIONALMIG2011    2875 non-null float64
RINTERNATIONALMIG2012    2875 non-null float64
RINTERNATIONALMIG2013    2875 non-null float64
RINTERNATIONALMIG2014    2875 non-null float64
RINTERNATIONALMIG2015    2875 non-null float64
RDOMESTICMIG2011         2875 non-null float64
RDOMESTICMIG2012         2875 non-null float64
RDOMESTICMIG2013         2875 non-null float64
RDOMESTICMIG2014         2874 non-null float64
RDOMESTICMIG2015         2874 non-null float64
RNETMIG2011              2874 non-null float64
RNETMIG2012              2874 non-null float64
RNETMIG2013              2874 non-null float64
RNETMIG2014              2874 non-null float64
RNETMIG2015              2874 non-null float64
dtypes: float64(30), int64(68), object(2)
memory usage: 2.2+ MB

In [8]:
df['STNAME'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia'], dtype=object)

### Filter STNAME is 'Californa' and CENSUS2010POP is greater than 1000000

In [20]:
df[(df['STNAME'] == 'California') & (df['CENSUS2010POP'] > 1000000)]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
190,40,4,9,6,0,California,California,37253956,37254503,37334079,...,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065
191,50,4,9,6,1,California,Alameda County,1510271,1510261,1513754,...,-0.363660,2.488670,3.743636,4.436457,2.141452,6.535369,9.157917,10.954544,12.487898,10.059473
197,50,4,9,6,13,California,Contra Costa County,1049025,1049197,1052921,...,4.663239,3.700034,6.365248,6.132260,4.832798,8.380053,7.175457,10.159756,10.458090,9.114322
209,50,4,9,6,37,California,Los Angeles County,9818605,9818700,9826009,...,-4.999439,-4.071266,-4.332318,-5.394299,-6.027694,-0.007808,0.377510,0.578049,0.215038,-0.437481
220,50,4,9,6,59,California,Orange County,3010232,3010266,3017866,...,1.992772,0.618346,-0.491825,-2.374727,-3.182714,6.033306,4.395138,3.681764,2.407607,1.587398
223,50,4,9,6,65,California,Riverside County,2189641,2189760,2202286,...,6.363916,4.925650,3.948834,5.305197,5.042058,8.162679,6.577153,5.743560,7.395962,7.163032
224,50,4,9,6,67,California,Sacramento County,1418788,1418742,1422010,...,-0.715296,-0.434811,-0.596399,3.066772,2.757133,2.530132,2.775299,2.946265,7.099638,6.762082
226,50,4,9,6,71,California,San Bernardino County,2035210,2035212,2041642,...,0.127623,-3.169611,-4.886451,-0.857214,-2.263998,1.770161,-1.328273,-3.109952,1.136606,-0.176477
227,50,4,9,6,73,California,San Diego County,3095313,3095308,3104386,...,0.354751,0.235513,-0.246567,0.657077,-2.855045,4.382515,5.773072,4.745940,5.921091,2.770965
233,50,4,9,6,85,California,Santa Clara County,1781642,1781672,1786844,...,-1.425140,-1.369435,-1.015500,-3.972733,-5.284100,7.465602,7.292527,8.383125,6.572025,5.114203

### mena of CENSUS2010POP from some rows

In [25]:
df.loc[3:11]['CENSUS2010POP'].mean()

40219.333333333336

In [26]:
df.loc[14:23]['CENSUS2010POP'].sum()

340375